$script = <<-'SCRIPT'
sudo apt-get upgrade
sudo apt-get update -y
sudo apt-get install -y nginx
SCRIPT
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
   # creating a virtual machine ubuntu 
   # creating a private network with ip
   config.vm.network "private_network", ip: "192.168.10.100"
   config.vm.provision "shell", inline: $script
   end